#!/bin/bash
# set -x

# Place this file at: /etc/bash_completion.d/my
# NOTE: Run the following commands with sudo level:
# curl -o /etc/bash_completion.d/my https://raw.githubusercontent.com/jerrens/MyCE/refs/heads/main/bash-completion/my
# chmod +x /etc/bash_completion.d/my
# exec bash
# 
# If not automatically loaded, add the following line to your .bashrc:
# source /etc/bash_completion.d/my
#   -- OR, to load all files in that directory, add the following line to your .bashrc:
# for f in /etc/bash_completion.d/*; do source "/etc/bash_completion.d/$f"; done

_my_autocomplete() {
    _cmds=$(my list)

    local cur
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    actions="definition list help version update set"

    # echo "cur = ${cur}" >> ~/my-autocomplete.log

    if ((COMP_CWORD == 1)); then
        COMPREPLY=( $(compgen -W "${actions} ${_cmds}" -- "${cur}") )
        # echo "  Reply ${COMPREPLY}" >> ~/my-autocomplete.log
        return 0;
    fi

    if ((COMP_CWORD >= 2)); then
        # If the first word is the option for a dryrun, then remove it
        if [[ "${COMP_WORDS[1]}" == "-d" ]]; then
            # echo -e "\nRemoving dryrun option from COMP_WORDS: Was - ${COMP_WORDS[@]}"
            unset 'COMP_WORDS[1]'
            COMP_WORDS=("${COMP_WORDS[@]}") # Reindex the array
            # echo -e "\nNow - ${COMP_WORDS[@]}\n"
        fi

        cur_action="${COMP_WORDS[1]}"

	# echo -e "\n  Action: ${cur_action}; CUR: ${cur}"

        case "${cur_action}" in
            definition)
                _all_cmds=$(my list -a)
                COMPREPLY=( $(compgen -W "${_all_cmds}" -- "${cur}") )
                return 0;;

            list)
                COMPREPLY=( $(compgen -W "-l -a" -- "${cur}") )
                return 0;;
            #set)
                # Show available variables from the .myCommand files
                #if ((COMP_CWORD >= 3)); then
                #    COMPREPLY=( $(compgen -W "todo" == ${cur}) )
                #fi
                #return 0;;

            help|verson|update)
                # No other options expected
                return 0;;

            *)
                COMPREPLY=( $(compgen -W "${_cmds}" -- "${cur}") )
                # echo "  Reply ${COMPREPLY}" >> ~/my-autocomplete.log
                return 0;;
        esac
    fi

    COMPREPLY=( $(compgen -W "${_cmds}" -- "${cur}") )
    return 0
}

# echo "Loading my autocomplete" >> ~/my-autocomplete.log
complete -o default -F _my_autocomplete my
